---
sudo: required
language: python
python: "2.7"
services:
- docker
 
before_install:
- sudo apt-get -qq update
- sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine libffi-dev

install:
- cd /tmp/
- git clone https://github.com/kamaxeon/ansible-role-libmbus.git libmbus
- cd libmbus
- pip install -r requirements.txt

script:
- molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
