---
sudo: required
language: python
python: "2.7"
services:
- docker
cache: pip
env:
  - ANSIBLE_VERSION=2.0.2.0
  - ANSIBLE_VERSION=2.1.4.0
  - ANSIBLE_VERSION=2.2.1.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine libffi-dev

install:
  - cp -a ~/build/kamaxeon/ansible-role-libmbus ~/libmbus
  - cd ~/libmbus
  - sed -i '/ansible==/d' requirements.txt

script:
  - pip install -r requirements.txt ansible==$ANSIBLE_VERSION
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
