---
- name:  Ensure base packages are installed
  package:
      name={{item}}
      state=present
  with_items: "{{ libmbus_base_packages }}"

# - name: Ensure git repository is downloaded
#   git:
#     repo: "{{ libmbus_repo }}"
#     dest: "{{ libmbus_dest }}"
#
